providers:
  google_drive: 
    plan: "Google One 200GB (sample)"
    base_usd_per_month: 2.99
    included_gb: 200
    overage_usd_per_gb: 0.03
    archive_usd_per_gb: 0.01
  dropbox:
    plan: "Plus 2TB (sample)"
    base_usd_per_month: 11.99
    included_gb: 2000
    overage_usd_per_gb: 0.02
    archive_usd_per_gb: 0.008
  onedrive:
    plan: "Microsoft 365 1TB (sample)"
    base_usd_per_month: 6.99
    included_gb: 1000
    overage_usd_per_gb: 0.02
    archive_usd_per_gb: 0.009
  icloud:
    plan: "iCloud+ 200GB (sample)"
    base_usd_per_month: 2.99
    included_gb: 200
    overage_usd_per_gb: 0.03
    archive_usd_per_gb: 0.012
  local:
    plan: "Local Storage (sample)"
    base_usd_per_month: 0.00
    included_gb: 999999
    overage_usd_per_gb: 0.00
    archive_usd_per_gb: 0.00
notes: "Sample pricing only for simulation."
